CREATE TABLE IF NOT EXISTS POST_REPLY (
    id SERIAL PRIMARY KEY,
    postid INTEGER REFERENCES post(id) ON DELETE CASCADE,
    userid INTEGER REFERENCES app_user(id) ON DELETE CASCADE,
    reply TEXT NOT NULL,
    create_time TIMESTAMP WITHOUT TIME ZONE DEFAULT current_timestamp
);